version: '3.8'

services:
  portfolio-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: k8s-terraform-portfolio
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=K8s-Terraform Portfolio Demo
      - APP_VERSION=1.0.0
      - ENVIRONMENT=development
      - FLASK_DEBUG=false
      - PORT=5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

